# permissions for end users to view zigbees.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zigbee-viewer-role
rules:
- apiGroups:
  - home.teaglebuilt.tech
  resources:
  - zigbees
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - home.teaglebuilt.tech
  resources:
  - zigbees/status
  verbs:
  - get
