# permissions for end users to edit zigbees.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zigbee-editor-role
rules:
- apiGroups:
  - home.teaglebuilt.tech
  resources:
  - zigbees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - home.teaglebuilt.tech
  resources:
  - zigbees/status
  verbs:
  - get
